import type { Metadata } from 'next';
import './globals.css';
import '@radix-ui/themes/styles.css';
import { inter } from '../ui/fonts';
import { ThemeContextProvider } from '../context/theme-context';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className="!scroll-smoot"
    >
      <body
        className={`${inter.className} bg-light-mode text-gray-950 relative pt-28 sm:pt-36 dark:bg-dark-mode dark:text-gray-50 dark:text-opacity-90`}
      >
        <ThemeContextProvider>{children}</ThemeContextProvider>
      </body>
    </html>
  );
}
